on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Decode GPG key
        id: gpg
        run: |
          echo "$SIGNING_KEY" | base64 --decode > /tmp/ci.asc
          gpg --quiet --output /tmp/ci.gpg --dearmor /tmp/ci.asc
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}

      - name: Build and Publish
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_SECRET_KEY_RING_FILE: /tmp/ci.gpg
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_githubUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_githubPassword: ${{ github.token }}
        run: ./gradlew publish --no-configure-on-demand --no-daemon --stacktrace
